### ISSUE TITLE
Files do not copy when there are no files in the destination path

### ISSUE THREAD

**Issue by Zuldan** [mgreenegit/xRobocopy#11]
If you take the example below. If there are no files or directories in C:\Temp, then xRobocopy does not copy files from \myserver\myfiles. As soon as you place a file or folder in C:\Temp and run the resource again, all files from \myserver\myfiles are copied to C:\Temp.

```
    xRobocopy CopyMyFiles
    {
        SubdirectoriesIncludingEmpty = $True
        Source                       = "\\myserver\myfiles"
        Destination                  = "C:\Temp"
    }
```

**Comment by fredgate** [comment]
I have similar problem if the source directory contains only sub directories and no file : nothing is copied. If I had a dummy file in the source directory, then the source directory is well copied.
