### ISSUE TITLE
robocopy resource throws access denied error

### ISSUE THREAD

**Issue by aravindabiswal** [mgreenegit/xRobocopy#13]
Hi Team,

I am trying to copy some files from a pullserver to target node through xRobocopy package in DSC.
The resource throws access denied error even if the robocopy command works fine in command prompt as well as in powershell window.

here is the code:

xRobocopy CopyMSI
        {
            Source = "\xxxxxxxxxxxx\xxx_Share"
            Destination = "X\Mxx"
            MultiThreaded = $false
            Restartable = $false
            AdditionalArgs = '/DCOPY:T /MIR /LOG:"D:\robo.txt"'
        }

I am running the command in Admin mode and the source folder in pullserver is shared with all and the servers are in same domain.

Please let me know if I am missing some parameter or there is some issue with the package.
If you have any working copy of the package in DSC , kindly share it.

Thanks,
Aravinda

**Comment by Arturas-K** [comment]
You are probably missing: PsDscRunAsCredential parameter, in example this was incorrectly spelled.
In PR #16 i have update example file and documentation to reference this common parameter correctly.
