### ISSUE TITLE
Running xRobocopy in a loop and getting an error

### ISSUE THREAD

**Issue by edycus** [mgreenegit/xRobocopy#27]
The below errors occurs when I run the robocopy command in a foreach loop. I am install two instances of SQL on a server and I copy the install files down from a file server before installing. 

Error Message: The resources ('[xRobocopy]SqlServerCopyDEVSQLInstance1' and '[xRobocopy]SqlServerCopyQASQLInstance2') have conflicting values of the following properties: 'AdditionalArgs'. Ensure that their values match.

        foreach ($SQLInstance in $node.SQLInstanceConfig) 
        {
            xRobocopy ('SqlServerCopy{0}' -f $SQLInstance.SQLInstanceName)
            {
                Source        = "\\FileServer\Software\" + $SQLInstance.SourcePath
                Destination   = "Drive:\Folder\Software\" + $SQLInstance.SourcePath
                AdditionalArgs = @('/E') #Recursive
                MultiThreaded = $true
                Restartable   = $true
            } 
      }

**Comment by johlju** [comment]
Source and Destination must have been set to the same path in both resource configurations ('SqlServerCopyDEVSQLInstance1' and 'SqlServerCopyQASQLInstance2'). You get this error message when two resource is configured with the same keys.
