### ISSUE TITLE
Add Ensure read only property and return it from Get-TargetResource

### ISSUE THREAD

**Issue by KarolKaczmarek** [mgreenegit/xRobocopy#6]
A common pattern for resources which operate on source/destination is to add Ensure property (even if it's read only if we don't support removal) similarly to File resource.
 Get-TargetResource would return Source and Destination with values specified in the configuration (always, not only if they exist or not - as it happens currently) and Ensure would be set to either "Present" or "Absent" based on the current state of the resource on the given node.

**Comment by mgreenegit** [comment]
Although I follow the pattern, is 'Ensure' the best term if we the purpose is to be an indicator?  Perhaps a ready only property 'Status' or 'State' or 'Present' with a Boolean value?

**Comment by KarolKaczmarek** [comment]
I agree this is not the best term for it, but not sure if we should be inventing new term for same thing now once we use it in so many places.

@joeyaiello @HemantMahawar thoughts?

**Comment by Arturas-K** [comment]
@KarolKaczmarek this can be closed in #16 PR i have added readonly parameter $Ensure, that is returned by Get function.

**Comment by KarolKaczmarek** [comment]
Thanks @Arturas-K
